In [10]:
import paho.mqtt.client as mqtt
import json
import numpy as np
import xgboost as xgb
from numpy import linalg
import socket
from scipy.stats import zscore, mode

# Regressor

In [ ]:
model = xgb.XGBRegressor()
model.load_model("./xbg_regressor.json")

# Callback chamado quando o cliente recebe a resposta CONNACK do servidor.
def on_connect(client, userdata, flags, rc):
    print("Conectado com o código de resultado "+str(rc))
    client.subscribe("/gw/ac233fc09283/status")
    
    
# Callback chamado quando uma mensagem PUBLISH é recebida do servidor.
#antenna array configuration: 2,2,0,5,6,1,12,14

def on_message(client, userdata, msg):
    
    data = json.loads(msg.payload)
        
    iqs = np.array([data[1]["aoa"]["iq"][i:i+6] for i in range(16,len(data[1]["aoa"]["iq"]),6)][:-1])
    print(iqs)
    model_predictions= []

    for elemnt in iqs:
        model_predictions.append(model.predict(elemnt.reshape(1,6)))
    model_predictions=np.array(model_predictions)
    #print(f"zscore={zscore(model_predictions)}")
    print(model_predictions)
#    print(f"Media {np.mean(model_predictions)} \t Media filtrada {np.mean(model_predictions[abs(zscore(model_predictions)) <1])}")


client = mqtt.Client()
client.on_connect = on_connect
client.on_message = on_message

# client.connect("broker.hivemq.com", 1883, 60)
client.connect("test.mosquitto.org", 1883, 60)

client.loop_forever()

# Classifier

In [14]:
model = xgb.XGBClassifier()
model.load_model("./xgb_classifier.json")

# Callback chamado quando o cliente recebe a resposta CONNACK do servidor.
def on_connect(client, userdata, flags, rc):
    print("Conectado com o código de resultado "+str(rc))
    client.subscribe("/gw/ac233fc09283/status")
    
    
# Callback chamado quando uma mensagem PUBLISH é recebida do servidor.
#antenna array configuration: 2,2,0,5,6,1,12,14

def on_message(client, userdata, msg):
    
    data = json.loads(msg.payload)
        
    iqs = np.array([data[1]["aoa"]["iq"][i:i+6] for i in range(16,len(data[1]["aoa"]["iq"]),6)][:-1])
    print(iqs)
    model_predictions= []

    for elemnt in iqs:
        model_predictions.append(model.predict(elemnt.reshape(1,6)))
    model_predictions=np.array(model_predictions)
    #print(f"zscore={zscore(model_predictions)}")
    print(mode(model_predictions)[0]*15)
#    print(f"Media {np.mean(model_predictions)} \t Media filtrada {np.mean(model_predictions[abs(zscore(model_predictions)) <1])}")


client = mqtt.Client()
client.on_connect = on_connect
client.on_message = on_message

# client.connect("broker.hivemq.com", 1883, 60)
client.connect("test.mosquitto.org", 1883, 60)

client.loop_forever()

Conectado com o código de resultado 0
[[ -85  -59   34   87   18  -51]
 [  11  106   53  -81  -49   18]
 [  68  -76  -95   15   43   28]
 [-101  -10   67   68  -12  -53]
 [  57   88    0  -95  -35   41]
 [  37 -104  -75   62   52    1]
 [-103   31   98   13  -34  -43]
 [  92   43  -47  -89   -6   53]
 [ -38  -96  -27   87   48  -23]
 [ -58   90   88  -39  -48  -19]
 [ 103   -1  -85  -54   20   49]]
[[105]]


C:\Users\pedro\AppData\Local\Temp\ipykernel_25136\1880876868.py:25: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  print(mode(model_predictions)[0]*15)


[[ 158  109  -47 -153   45   76]
 [ -38 -196  -82  134   19  -86]
 [-142  138  158  -22  -82   33]
 [ 195   36 -116 -117   74   44]
 [-118 -164   -1  162  -28  -85]
 [ -39  193  128  -92  -57   70]
 [ 183  -81 -163  -41   91  -10]
 [-180  -74   74  146  -69  -58]
 [  67  178   62 -146   -7   87]
 [  94 -169 -151   68   71  -50]
 [-196   33  145   75  -86  -14]]
[[90]]
[[ 196  -37 -157  -79   94   10]
 [-157 -123   24  175  -58  -76]
 [  40  198   85 -148  -26   83]
 [ 161 -126 -179   -6   84  -37]
 [-199   -9  117  119  -88  -38]
 [ 120  159    6 -176   20   85]
 [  38 -195 -143  105   54  -73]
 [-177   92  169   44  -90   12]
 [ 180   81  -82 -152   66   63]
 [ -63 -190  -48  170    5  -91]
 [-112  165  163  -65  -71   56]]
[[90]]
[[  81 -295 -258  114  173 -132]
 [-278  113  255  126 -210  -70]
 [ 285  103  -71 -288  113  178]
 [ -47 -288 -190  224   86 -198]
 [-174  249  291  -67 -201   85]
 [ 302  -21 -238 -176  190  109]
 [-243 -179   -5  292  -38 -216]
 [ -39  295  230 -182 -162 

KeyboardInterrupt: 